# Generated by Django 4.0.5 on 2022-06-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigos',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='amigos',
            name='profesion',
        ),
    ]
