# Generated by Django 4.0.5 on 2022-06-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0002_remove_amigos_apellido_remove_amigos_profesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='profesion',
        ),
    ]
