# Generated by Django 4.0.5 on 2022-06-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0003_remove_familiar_apellido_remove_familiar_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='entregables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('fechaDeFabricacion', models.DateField()),
                ('servis', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='amigos',
            name='tieneEmpleo',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='tieneEmpleo',
        ),
    ]
