# Generated by Django 4.0.5 on 2022-06-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0004_entregables_remove_amigos_tieneempleo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entregables',
            new_name='auto',
        ),
    ]
