# Generated by Django 4.0.5 on 2022-06-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0005_rename_entregables_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fechaDeNacimiento',
        ),
    ]
