# Generated by Django 4.0.5 on 2022-06-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0006_remove_familiar_fechadenacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='fechaDeFabricacion',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='servis',
        ),
        migrations.AddField(
            model_name='auto',
            name='numeroPatente',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
